version: '3.8'

services:
  # PostgreSQL database service
  postgres:
    image: postgres:15-alpine
    container_name: nachonekobot_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-nachonekobot}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database_setup.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # NachonekoBot application service
  app:
    image: ghcr.io/kimmyxyc/nachonekobot-v2:main
    container_name: nachonekobot_app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      # Database connection settings
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-nachonekobot}
      # Application settings
      DYNACONF_APP__DEBUG: ${DEBUG:-false}
    volumes:
      - ./conf_dir:/app/conf_dir
      - ./data:/app/data
      - ./run.log:/app/run.log
      - ./.env:/app/.env
    restart: unless-stopped

volumes:
  postgres_data:
